import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService, Report, Trip, User } from '../../services/api.service';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="page">
      <div class="page-header">
        <h2>Reports</h2>
        <button (click)="toggleForm()">{{ showForm ? 'Cancel' : '+ Generate Report' }}</button>
      </div>

      @if (error) {
        <div class="error">{{ error }}</div>
      }

      @if (showForm) {
        <div class="form-box">
          <h3>Generate Report</h3>
          <p style="color:#555;font-size:14px">Sums all expenses for the selected trip and saves the result.</p>
          <form (ngSubmit)="generate()">
            <label>Trip
              <select [(ngModel)]="genTripId" name="trip_id" required>
                <option [value]="0" disabled>Select trip</option>
                @for (t of trips; track t.trip_id) {
                  <option [value]="t.trip_id">{{ t.destination }} ({{ t.start_date }})</option>
                }
              </select>
            </label>
            <label>Generated By
              <select [(ngModel)]="genUserId" name="generated_by" required>
                <option [value]="0" disabled>Select user</option>
                @for (u of users; track u.user_id) {
                  <option [value]="u.user_id">{{ u.first_name }} {{ u.last_name }}</option>
                }
              </select>
            </label>
            <div class="form-actions">
              <button type="submit">Generate</button>
              <button type="button" (click)="toggleForm()">Cancel</button>
            </div>
          </form>
        </div>
      }

      <!-- Filter bar -->
      <div class="filter-bar">
        <label>From<input [(ngModel)]="filterFrom" name="filterFrom" type="date" (change)="load()" /></label>
        <label>To<input [(ngModel)]="filterTo" name="filterTo" type="date" (change)="load()" /></label>
        <button type="button" (click)="clearFilters()">Clear</button>
      </div>

      <!-- Summary stats -->
      @if (!loading && reports.length > 0) {
        <div class="stats-row">
          <div class="stat-card">
            <div class="stat-value">{{ reports.length }}</div>
            <div class="stat-label">Total Reports</div>
          </div>
          <div class="stat-card">
            <div class="stat-value">{{ '$' + totalExpenses() }}</div>
            <div class="stat-label">Total Expenses</div>
          </div>
          <div class="stat-card">
            <div class="stat-value">{{ '$' + avgExpenses() }}</div>
            <div class="stat-label">Avg per Report</div>
          </div>
        </div>
      }

      @if (loading) {
        <p>Loading...</p>
      } @else {
        <table>
          <thead>
            <tr>
              <th>ID</th><th>Trip</th><th>Generated By</th><th>Total Expenses</th><th>Status</th><th>Generated At</th><th>Actions</th>
            </tr>
          </thead>
          <tbody>
            @for (r of reports; track r.report_id) {
              <tr>
                <td>{{ r.report_id }}</td>
                <td>{{ r.destination }}</td>
                <td>{{ r.generated_by_name }}</td>
                <td>{{ '$' + r.total_expenses }}</td>
                <td><span class="badge report-{{ r.report_status?.toLowerCase() }}">{{ r.report_status }}</span></td>
                <td>{{ r.generated_at }}</td>
                <td class="actions">
                  @if (r.report_status === 'PENDING') {
                    <button class="btn-submit" (click)="updateStatus(r.report_id!, 'SUBMITTED')">Submit</button>
                  }
                  @if (r.report_status === 'SUBMITTED') {
                    <button class="btn-approve" (click)="updateStatus(r.report_id!, 'APPROVED')">Approve</button>
                  }
                  <button class="btn-delete" (click)="delete(r.report_id!)">Delete</button>
                </td>
              </tr>
            } @empty {
              <tr><td colspan="7" class="empty">No reports found.</td></tr>
            }
          </tbody>
        </table>
      }
    </div>
  `
})
export class ReportsComponent implements OnInit {
  reports: Report[] = [];
  trips: Trip[] = [];
  users: User[] = [];
  loading = true;
  error = '';
  showForm = false;
  genTripId = 0;
  genUserId = 0;
  filterFrom = '';
  filterTo = '';

  constructor(private api: ApiService, private cdr: ChangeDetectorRef) {}

  ngOnInit() {
    this.api.getTrips().subscribe({ next: (t) => { this.trips = t; this.cdr.detectChanges(); } });
    this.api.getUsers().subscribe({ next: (u) => { this.users = u; this.cdr.detectChanges(); } });
    this.load();
  }

  load() {
    this.loading = true;
    this.api.getReports(this.filterFrom || undefined, this.filterTo || undefined).subscribe({
      next: (data) => { this.reports = data; this.loading = false; this.cdr.detectChanges(); },
      error: (err) => { this.error = err.message; this.loading = false; this.cdr.detectChanges(); }
    });
  }

  clearFilters() {
    this.filterFrom = '';
    this.filterTo = '';
    this.load();
  }

  totalExpenses(): string {
    return this.reports.reduce((sum, r) => sum + Number(r.total_expenses || 0), 0).toFixed(2);
  }

  avgExpenses(): string {
    if (!this.reports.length) return '0.00';
    return (this.reports.reduce((sum, r) => sum + Number(r.total_expenses || 0), 0) / this.reports.length).toFixed(2);
  }

  toggleForm() {
    this.showForm = !this.showForm;
    if (!this.showForm) { this.genTripId = 0; this.genUserId = 0; }
  }

  generate() {
    this.api.createReport({ trip_id: this.genTripId, generated_by: this.genUserId }).subscribe({
      next: () => { this.showForm = false; this.genTripId = 0; this.genUserId = 0; this.cdr.detectChanges(); this.load(); },
      error: (err) => { this.error = err.error?.error || err.message; this.cdr.detectChanges(); }
    });
  }

  updateStatus(id: number, status: string) {
    this.api.updateReportStatus(id, status).subscribe({
      next: () => this.load(),
      error: (err) => { this.error = err.error?.error || err.message; this.cdr.detectChanges(); }
    });
  }

  delete(id: number) {
    if (confirm('Delete this report?')) {
      this.api.deleteReport(id).subscribe({
        next: () => this.load(),
        error: (err) => { this.error = err.error?.error || err.message; }
      });
    }
  }
}
